# Generated by Django 5.2.7 on 2025-10-18 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя читателя')),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('publication_year', models.IntegerField(verbose_name='Год публикации')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитана')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_date', models.DateField(auto_now_add=True, verbose_name='Дата прочтения')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.reader')),
            ],
            options={
                'verbose_name': 'Чтение',
                'verbose_name_plural': 'Чтения',
            },
        ),
        migrations.AddField(
            model_name='reader',
            name='books',
            field=models.ManyToManyField(through='lab3.Reading', to='lab3.book', verbose_name='Книги'),
        ),
    ]
