# Generated by Django 5.2.7 on 2025-10-18 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Бюджет')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('hire_date', models.DateField(verbose_name='Дата найма')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab4.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='Роль в проекте')),
                ('assignment_date', models.DateField(auto_now_add=True, verbose_name='Дата назначения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab4.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab4.project')),
            ],
            options={
                'verbose_name': 'Назначение на проект',
                'verbose_name_plural': 'Назначения на проекты',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(through='lab4.ProjectAssignment', to='lab4.employee', verbose_name='Сотрудники'),
        ),
    ]
